server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-user?useSSL=false
    username: root
    password: qwer1234
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: userservice
#  cloud:
#    nacos:
#      server-addr: localhost:8848 # nacos服务地址
#      discovery:
#        cluster-name: HZ # 集群
mybatis:
  type-aliases-package: com.roydon.order.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.roydon: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS